Create the empty assets dir in the right place.
Fixes #53.

diff --git a/tools/flashdevelop/build-fdz b/tools/flashdevelop/build-fdz
--- a/tools/flashdevelop/build-fdz
+++ b/tools/flashdevelop/build-fdz
@@ -7,11 +7,19 @@ set -e
 PLUGIN_ROOT=`readlink -f $(dirname $0)`
 cd "$PLUGIN_ROOT"
 
+BASE_DIR='$(BaseDir)/Projects/380 HaXe - Flambe Project'
+
+# Sanity check
+if [ ! -d "$BASE_DIR" ]; then
+    echo "Could not find directory: $BASE_DIR"
+    exit 1
+fi
+
 FDZ="flambe-FlashDevelop.fdz"
 rm -f "$FDZ"
 git ls-files '$(BaseDir)' | zip "$FDZ" -@
 
 # Include an empty assets directory, since git can't handle empty dirs
-ASSET_DIR='$(BaseDir)/Projects/401 HaXe - Flambe Project/assets/bootstrap'
+ASSET_DIR="$BASE_DIR/assets/bootstrap"
 mkdir -p "$ASSET_DIR"
 zip "$FDZ" "$ASSET_DIR"
